# Generated by Django 5.2.7 on 2025-11-28 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('TENS', 'tens'), ('AMBULANCIA', 'ambulancia'), ('MEDICO', 'medico')], max_length=30),
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('tipo_prevision', models.CharField(choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('DIPRECA', 'DIPRECA'), ('PARTICULAR', 'PARTICULAR')], max_length=10)),
                ('accidente_laboral', models.BooleanField()),
                ('motivo_derivacion', models.TextField()),
                ('prestacion_requerida', models.TextField()),
                ('gravedad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('evaluacion', models.TextField()),
                ('temperatura', models.FloatField()),
                ('presion_arterial', models.TextField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('saturacion_oxigeno', models.IntegerField()),
                ('antecedentes', models.TextField()),
                ('alergias', models.TextField()),
                ('pendiente', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('medico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_asignadas', to='gestion.usuario')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('derivacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_modificaciones', to='gestion.derivacion')),
                ('usuario_modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.usuario', verbose_name='Usuario Modificador')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('comorbilidades', models.ManyToManyField(to='gestion.comorbilidad')),
            ],
        ),
        migrations.AddField(
            model_name='derivacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente'),
        ),
    ]
