# Generated by Django 5.2.7 on 2025-11-20 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_comorbilidad_alter_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('derivacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_modificaciones', to='gestion.derivacion')),
                ('usuario_modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.usuario', verbose_name='Usuario Modificador')),
            ],
        ),
    ]
