# Generated by Django 5.2.6 on 2025-10-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=32)),
            ],
        ),
    ]
